# Generated by Django 3.1 on 2020-08-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200822_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='question',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
