# Generated by Django 3.1 on 2020-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200822_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
